<img id="mountainHigher" />
<img id="city" />
<img id="mountainLower" />
<img id="forest" />
<img id="river" />
<img id="hillHigher" />
<img id="water" />
<img id="hillLower" />
<img id="road" />
<img id="cycle" />
<img id="standing" />
<img id="wheel_1" />
<img id="wheel_2" />
<img id="leavesShadow" />
<img id="tree" />
<img id="leaves" />
<img id="grass" />
<canvas id="Decoration"></canvas>